[project]
name = "rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.2"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "seaborn>=0.13.2",
    "torch",
    "hockey",
    "pink-noise-rl",
    "wandb>=0.24.0",
    "coloredlogs>=15.0.1",
    "rich>=14.3.1",
    "comprl",
    "python-dotenv>=1.2.1",
    "numba",
    "torchcfm>=1.0.7",
    "stable-baselines3>=2.7.1",
    "pandas>=2.3.3",
    "opencv-python>=4.13.0.92",
    "moviepy>=2.2.1",
]

# --- Fix for Pascal Support ---
[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu126" }]
torchvision = [{ index = "pytorch-cu126" }]
hockey = { path = "./hockey-env", editable = true }
pink-noise-rl = { path = "./pink-noise-rl", editable = true }
comprl = { git = "https://github.com/martius-lab/teamproject-competition-server.git", subdirectory = "comprl" }
